function [ materialIndexes, materialNames, mapTissueTemp, mapBoneTemp] = loadPantomMaterialInfo( p, phanMaterialType )
% function [ materialIndexes, materialNames, mapTissueTemp, mapBoneTemp] = loadPantomMaterialInfo( p, phanMaterialType )
%
% Implemeted material mapping names:
%   1. Simple phantom: 
%       'v1-water'
%       'v1-tissue' 
%       'v2-water-bone'
%       'v3-tissue-bone'
%       'v3-tissue-tissue'
%       'v5-mult-beamhardening'
%       'v5-brain-iodine'
%   2. CatPhan
%       'Catphan-sensitivity'
%       'Catphan-contrast'
%       'Catphan-uniform'
%       'Catphan-geometry'
%       'Catphan-resolution'
%       'Catphan-resolution-bone'
%   3. XCAT phantom:
%       'v4-XCAT-lung'
%       'v4-XCAT-head'
%       'v6-XCAT-liver'
%
% Meng Wu at Stanford University
% 2014 - 2015


mapTissueTemp = zeros( size( phanMaterialType), 'single' );
mapBoneTemp = zeros( size( phanMaterialType), 'single' );

if strcmpi(p.Phantom.materialMappingName, 'v1-water')
    
    materialIndexes = { 1 };
    materialNames = { ...
        'water'
        };   

elseif strcmpi(p.Phantom.materialMappingName, 'v1-tissue')
    
    materialIndexes = { 1 };
    materialNames = { ...
        'Tissue_Soft_ICRU-44'
        };   
    
elseif strcmpi(p.Phantom.materialMappingName, 'v2-water-bone')
    
    materialIndexes = { 1, 2 };
    materialNames = { ...
        'water', ...
        'bone_compact' ...
        };
    
elseif strcmpi(p.Phantom.materialMappingName, 'v3-tissue-bone') 
    
    materialIndexes = {0, 1, 2};
    materialNames = { ...
        'Air_Dry_near_sea_level', ...
        'Tissue_Soft_ICRU-44', ...
        'Bone_Cortical_ICRU-44', ...
        };
    
    mapTissueTemp( phantomMaterials == 1 ) = 1;
    mapBoneTemp( phantomMaterials == 2 ) = 1;
    
elseif strcmpi(p.Phantom.materialMappingName, 'v3-tissue')
    
    materialIndexes = {0, 1, 2};
    materialNames = { ...
        'Air_Dry_near_sea_level', ...
        'Tissue_Soft_ICRU-44', ...
        'Tissue_Soft_ICRU-44', ...
        };
    
    mapTissueTemp( phantomMaterials == 1 |  phantomMaterials == 2 ) = 1;
    mapBoneTemp( phantomMaterials == 2 ) = 1;
    
elseif strcmpi(p.Phantom.materialMappingName, 'v5-mult-beamhardening') 
    
    materialIndexes = {0, 1, 2, 3, 4, 5};
    materialNames = { ...
        'Air_Dry_near_sea_level', ...
        'Tissue_Soft_ICRU-44', ...
        'B-100_Bone-Equivalent_Plastic', ...
        'Aluminum'...
        'Bone_Cortical_ICRU-44', ...
        'Ca', ...
        };
    
    mapTissueTemp( phantomMaterials == 1 ) = 1;
    mapBoneTemp( phantomMaterials == 2 ) = 1;        
    
elseif strcmpi(p.Phantom.materialMappingName, 'v5-brain-iodine') 
    
    materialIndexes = {0, 1, 2, 3, 4};
    materialNames = { ...
        'air', ...
        'water', ...
        'brain', ...
        'bone_cortical', ...
        'I', ...
        };
    
    mapTissueTemp( phantomMaterials == 1 ) = 1;
    mapBoneTemp( phantomMaterials == 2 ) = 1;
    
elseif strcmpi(p.Phantom.materialMappingName, 'Catphan-sensitivity')
    
    materialIndexes = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14 };
    materialNames = { ...
        'water', ...
        'Acrylic', ...
        'Bone50', ...
        'Acrylic', ...
        'PMP', ...
        'air', ...
        'lung', ...
        'Delrin', ...
        'Polystryrene', ...
        'Teflon', ...
        'Bone20', ...
        'LDPE', ...
        'Acrylic', ...
        };
    
elseif strcmpi(p.Phantom.materialMappingName, 'Catphan-contrast') || strcmpi(p.Phantom.materialMappingName, 'Catphan-uniform')
    
    materialIndexes = { 1 };
    materialNames = { ...
        'water' ...
        };
    
elseif strcmpi(p.Phantom.materialMappingName, 'Catphan-geometry')
    
    materialIndexes = { 1, 100 };
    materialNames = { ...
        'water', ...
        'Iron' ...
        };
    
elseif strcmpi(p.Phantom.materialMappingName, 'Catphan-resolution')
    
    materialIndexes = { 1, 2 };
    materialNames = { ...
        'water', ...
        'Titanium' ...
        };    
    
elseif strcmpi(p.Phantom.materialMappingName, 'Catphan-resolution-bone')
    
    materialIndexes = { 1, 2 };
    materialNames = { ...
        'water', ...
        'bone_cortical' ...
        };  
    
elseif strcmpi(p.Phantom.materialMappingName, 'v4-XCAT-lung')
    
    materialIndexes = {1, 2, 3, 4};
    materialNames = { ...
        'Lung_Tissue_ICRU-44', ...
        'Tissue_Soft_ICRU-44', ...
        'B-100_Bone-Equivalent_Plastic', ...
        'Bone_Cortical_ICRU-44' ...
        };
    
    mapTissueTemp( phanMaterialType == 2 ) = 1;
    mapBoneTemp( phanMaterialType == 3 | phanMaterialType == 4 ) = 1;
    
elseif strcmpi(p.Phantom.materialMappingName, 'v4-XCAT-head')
    
    materialIndexes = {1, 2, 3, 4};
    materialNames = { ...
        'soft_tissue', ...
        'brain', ...
        'muscle_striated', ...
        'bone_cortical' ...
        };
    
    mapTissueTemp( phanMaterialType == 2 ) = 1;
    mapBoneTemp( phanMaterialType == 4 ) = 1;    
    
elseif strcmpi(p.Phantom.materialMappingName, 'v6-XCAT-liver')
    
    materialIndexes = {1, 2, 3, 4, 5, 6};
    materialNames = { ...
        'lung', ...
        'soft_tissue', ...
        'muscle_skeletal', ...
        'blood' ...
        'bone_compact', ...
        'bone_cortical' ...
        };
    
    mapTissueTemp( phanMaterialType == 4 ) = 1;
    mapBoneTemp( phanMaterialType == 5 | phanMaterialType == 6 ) = 1;
    
else
    
    error('Unknown phantom type selected!');
    
end


